# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  namespace: default
  labels:
    app: config-server-app
spec:
  selector:
    matchLabels:
      app: config-server-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
      - name: config-server-app
        image: 123joker/configserver:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9296
        env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address
                
---

# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
  namespace: default
spec:
  selector:
    app: config-server-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9296
---
