# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
  namespace: default
  labels:
    app: payment-service-app
spec:
  selector:
    matchLabels:
      app: payment-service-app
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: payment-service-app
        image: udemycourse/paymentservice
        ports:
        - containerPort: 8081
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: eureka_service_address
              name: eureka-cm
        - name: CONFIG_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: config_url
              name: eureka-cm
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
  namespace: default
spec:
  selector:
    app: payment-service-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8081
---
