# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  namespace: default
  labels:
    app: redis-app
spec:
  selector:
    matchLabels:
      app: redis-app
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: redis-app
        image: redis:7.0.4
        ports:
        - containerPort: 6379
        command:
          - "redis-server"
        args:
          - "--protected-mode"
          - "no"
---

# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-app
  ports:
  -  port: 6379
     targetPort: 6379
---
