# Application properties
spring:
  application:
    name: demo
  debug:
    enabled: true
#  datasource:
#    url:
#    driver-class-name: org.h2.Driver
#    username:
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update

# Server configuration
server:
  port: 8080